---
kind: pipeline
type: docker
name: pytest

steps:
  - name: build pytest
    image: python:3.13
    commands:
      - python --version
      - python -m pip install --upgrade pip setuptools wheel
      - cp config_sample.py config.py
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt
      - python -m py_compile banbot/*.py tests/*.py tests/integration/*.py
      - pytest --cov=banbot --cov-report=term-missing --cov-fail-under=55

trigger:
  branch:
    - main
  event:
    - push
    - tag
